Removes dependency on 'prologic/remark-lint:latest' and fix #44
reviewdog/action-remark-lint pull request #45
Opened 2021-09-01 13:36 UTC by rickstaa

This pull request removes the dependency on the 'prologic/remark-lint:latest' dockerfile base. This was done so that we can easier debug the action while also keeping all the packages up to date. This commit also adds a '.remarkrc' file to the `testdata` folder. It also fixes #44.

### Tests
- ✔️ Passed: https://github.com/rickstaa/action-test-repo/pull/61

2021-09-01 13:40 UTC, rickstaa commented
@asbjornu I went ahead and created a new `DockerFile`.  By doing this, #44 also seems to be fixed. I kept the code close to our original code since I am a bit short on time. In the future, we might want to transform it into bourne shell format (i.e., `sh`) to make the image a bit smaller. 

Let me know if there are any points you would like to improve or feel free to merge the pull request.

2021-09-01 13:42 UTC, rickstaa commented
@asbjornu I now attached the `bump:major` tag to the pull request since it is a big change. Feel free to replace this tag with the `bump:minor` if you think that reflects the size of the change better.

2021-09-01 13:43 UTC, rickstaa commented
Moment, I will fix the suggestions made by the hado-lint action.

2021-09-01 13:49 UTC, rickstaa commented on Dockerfile
> +RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}
Will be fixed in next commit.

2021-09-01 13:49 UTC, rickstaa commented on Dockerfile
> +RUN apk --no-cache add git bash
Fixed in next commit.

2021-09-01 13:52 UTC, rickstaa commented on Dockerfile
> +RUN npm install -g remark-cli remark-preset-lint-recommended remark-lint
@asbjornu I think it is nicer to keep these command separated as they do different things.

2021-09-01 13:55 UTC, rickstaa commented on Dockerfile
> +RUN npm install -g remark-cli remark-preset-lint-recommended remark-lint
@asbjornu I would the action to use the latest remark lint version. What do you think?

2021-09-01 13:55 UTC, rickstaa commented on Dockerfile
> +RUN npm install -g remark-cli@latest remark-preset-lint-recommended@latest remark-lint@latest
@asbjornu I think it is nicer to keep these command separated as they do different things.

2021-09-01 13:59 UTC, asbjornu commented on Dockerfile
> +RUN apk --no-cache add git bash~=5.1
Any reason to not pin the version of `git` here?

2021-09-01 13:59 UTC, asbjornu commented on Dockerfile
> +RUN npm install -g remark-cli@latest remark-preset-lint-recommended@latest remark-lint@latest
Agreed

2021-09-01 14:01 UTC, rickstaa commented
@asbjornu New tests also pass.

https://github.com/rickstaa/action-test-repo/pull/62

2021-09-01 14:02 UTC, asbjornu commented on Dockerfile
> +RUN npm install -g remark-cli remark-preset-lint-recommended remark-lint
I would prefer to pin the versions, but allow for them to be automatically updated by a GitHub Action (or Dependabot or Renovate or whatever supports it). I've created a [custom JSON based scheme for APT](https://github.com/SwedbankPay/jekyll-plantuml-docker/blob/main/.github/workflows/apt-update.yml).

2021-09-01 14:04 UTC, rickstaa commented on Dockerfile
> +RUN npm install -g remark-cli remark-preset-lint-recommended remark-lint
@asbjornu I think your solution is better. Do you have the time this week to implement that change?

2021-09-01 14:04 UTC, rickstaa commented on Dockerfile
> +RUN npm install -g remark-cli remark-preset-lint-recommended remark-lint
@asbjornu I think your solution is better. Do you have the time to implement that change?

2021-09-01 14:07 UTC, asbjornu commented on Dockerfile
> +RUN npm install -g remark-cli remark-preset-lint-recommended remark-lint
Yes, but they should not be breaking so we can do them later. Can you please pin to a specific version in this PR and I'll follow up with a JSON-based solution?

2021-09-01 14:44 UTC, asbjornu requested changes

2021-09-01 14:44 UTC, asbjornu commented on Dockerfile
> +RUN npm install -g remark-cli@latest remark-preset-lint-recommended@latest remark-lint@latest
Please pin to specific versions and I'll create an auto-update scheme in a future PR.

2021-09-02 07:32 UTC, rickstaa commented
Latest test results:
- ✔️ Passed: https://github.com/rickstaa/action-test-repo/pull/63#pullrequestreview-744705806

2021-09-02 07:33 UTC, rickstaa commented on Dockerfile
> +RUN apk --no-cache add git bash~=5.1
@asbjornu No, I'm happy to pin git aswell.

2021-09-02 07:48 UTC, asbjornu approved these changes

2021-09-02 07:49 UTC, merged

2021-09-02 07:49 UTC, asbjornu commented
Awesome!